# Generated by Django 3.1 on 2020-09-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chaos_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='network_mode_percent',
            field=models.IntegerField(null=True, verbose_name='network_mode_percent'),
        ),
    ]
