# Generated by Django 3.1 on 2020-09-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_statistic_network_mode_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaos',
            name='monitoring_config_params',
            field=models.TextField(blank=True, null=True, verbose_name='Отслеживаемые поля конфига'),
        ),
        migrations.AlterField(
            model_name='chaos',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='Текущий конфиг хаоса'),
        ),
    ]
