# Generated by Django 3.1 on 2020-09-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200928_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaos',
            name='compired_config',
            field=models.TextField(blank=True, null=True, verbose_name='Результат сравнения конфигов'),
        ),
        migrations.AddField(
            model_name='chaos',
            name='compired_config_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время сравнения конфигов'),
        ),
    ]
