# Generated by Django 3.1 on 2020-10-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200929_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaos',
            name='compired_config_errs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Расхождений в сравниваемых параметрах конфигов'),
        ),
        migrations.AddField(
            model_name='chaos',
            name='compired_config_warns',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Расхождений в параметрах конфигов'),
        ),
    ]
