# Generated by Django 3.1 on 2020-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201001_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaos',
            name='multimeter_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP-адрес мультиметра'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='voltage_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Средний вольтаж'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='voltage_current',
            field=models.FloatField(blank=True, null=True, verbose_name='Текущий вольтаж'),
        ),
    ]
