# Generated by Django 3.1 on 2020-10-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201001_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='voltage_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальный вольтаж'),
        ),
    ]
