# Generated by Django 3.1 on 2020-10-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201005_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaos',
            name='bat_reserved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отслеживать bat_reserved'),
        ),
    ]
