# Generated by Django 3.1 on 2020-10-06 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_chaos_bat_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawimgsreport',
            name='color',
            field=models.CharField(blank=True, default='RBW', max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длина строки должна равняться любым 3 символам: R,B,W', regex='^[WBR]{3}$')], verbose_name='Цвет отрисовки'),
        ),
        migrations.AddField(
            model_name='metricreport',
            name='color',
            field=models.CharField(blank=True, default='RBW', max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Длина строки должна равняться любым 3 символам: R,B,W', regex='^[WBR]{3}$')], verbose_name='Цвет отрисовки'),
        ),
    ]
