# Generated by Django 3.1 on 2020-10-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201006_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawimgsreport',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания отчета'),
        ),
        migrations.AlterField(
            model_name='netcompilereport',
            name='chaos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chaos', verbose_name='Хаос'),
        ),
    ]
