# Generated by Django 3.1 on 2020-10-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201006_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawimgsreport',
            name='chaos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chaos', verbose_name='Хаос'),
        ),
    ]
