# Generated by Django 3.1 on 2020-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201006_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawimgsreport',
            name='elapsed_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время отрисовки'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='final_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент отрисовки'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='max_inactive_time',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Предельное время бездействия'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='p995',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время отрисовки 99.5%'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='p999',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время отрисовки 99.9%'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='success_percent',
            field=models.FloatField(blank=True, default=100, null=True, verbose_name='Cчитать отрисовку успешной при, %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t10',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 10 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t100',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 100 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t110',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 110 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t120',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 120 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t130',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 130 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t140',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 140 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t150',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 150 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t20',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 20 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t30',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 30 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t40',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 40 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t50',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 50 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t60',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 60 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t70',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 70 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t80',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 80 мин., %'),
        ),
        migrations.AddField(
            model_name='drawimgsreport',
            name='t90',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрисовано за 90 мин., %'),
        ),
        migrations.AddField(
            model_name='metricreport',
            name='draw_inactive_time',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Предельное время бездействия отрисовки'),
        ),
        migrations.AddField(
            model_name='metricreport',
            name='draw_success_percent',
            field=models.FloatField(blank=True, default=100.0, null=True, verbose_name='Считать отрисовку успешной при, %'),
        ),
        migrations.AddField(
            model_name='metricreport',
            name='net_inactive_time',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Предельное время бездействия сборки сети'),
        ),
        migrations.AddField(
            model_name='metricreport',
            name='net_success_percent',
            field=models.FloatField(blank=True, default=100.0, null=True, verbose_name='Считать сборку сети успешной при, %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='elapsed_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время сборки сети'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='final_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент сборки сети'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='max_inactive_time',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Предельное время бездействия'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='p995',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время сборки 99.5%'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='p999',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время сборки 99.9%'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='success_percent',
            field=models.FloatField(blank=True, default=100, null=True, verbose_name='Считать сборку успешной при, %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t10',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 10 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t100',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 100 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t110',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 110 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t120',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 120 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t130',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 130 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t140',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 140 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t150',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 150 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t20',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 20 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t30',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 30 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t40',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 40 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t50',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 50 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t60',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 60 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t70',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 70 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t80',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 80 мин., %'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='t90',
            field=models.CharField(blank=True, max_length=100, verbose_name='Собранность сети за 90 мин., %'),
        ),
        migrations.AlterField(
            model_name='drawimgsreport',
            name='drawed_esl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отрисовано ценников, шт'),
        ),
        migrations.AlterField(
            model_name='drawimgsreport',
            name='not_drawed_esl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Не отрисовано, шт '),
        ),
        migrations.AlterField(
            model_name='metricreport',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время начала сбора статистики'),
        ),
        migrations.AlterField(
            model_name='metricreport',
            name='date_time_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания сбора статистики'),
        ),
        migrations.AlterField(
            model_name='netcompilereport',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время начала сборки'),
        ),
        migrations.AlterField(
            model_name='netcompilereport',
            name='date_time_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания сборки'),
        ),
    ]
