# Generated by Django 3.1 on 2020-10-09 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201008_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaos',
            name='date_time_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Время обновления данных'),
        ),
        migrations.AlterField(
            model_name='drawimgsreport',
            name='create_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Дата и время создания отчета'),
        ),
        migrations.AlterField(
            model_name='drawimgsstat',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Дата и время записи'),
        ),
        migrations.AlterField(
            model_name='metricreport',
            name='create_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Дата и время начала сбора статистики'),
        ),
        migrations.AlterField(
            model_name='netcompilationstat',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Дата и время записи'),
        ),
        migrations.AlterField(
            model_name='netcompilereport',
            name='create_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Дата и время начала сборки'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True, verbose_name='Дата и время'),
        ),
    ]
