# Generated by Django 3.1 on 2020-10-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201010_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawimgsreport',
            name='draw_imgs_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип отрисовки ценников'),
        ),
        migrations.AddField(
            model_name='metricreport',
            name='draw_imgs_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип отрисовки ценников'),
        ),
    ]
