# Generated by Django 3.1 on 2020-10-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_chaos_dat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaos',
            name='grafana_dashboard_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL дашборда в Grafana'),
        ),
    ]
