# Generated by Django 3.1 on 2020-11-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201031_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawimgsreport',
            name='voltage_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее значение потребления в процессе отрисовки'),
        ),
        migrations.AddField(
            model_name='metricreport',
            name='voltage_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее значение потребления (общее)'),
        ),
        migrations.AddField(
            model_name='netcompilereport',
            name='voltage_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее значение потребления в процессе сборки'),
        ),
    ]
