# Generated by Django 3.1 on 2020-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201109_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawimgsreport',
            name='voltage_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее значение потребления в процессе отрисовки, mA'),
        ),
        migrations.AlterField(
            model_name='metricreport',
            name='voltage_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее значение потребления (общее), mA'),
        ),
        migrations.AlterField(
            model_name='netcompilereport',
            name='voltage_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее значение потребления в процессе сборки, mA'),
        ),
    ]
