# Generated by Django 3.1 on 2020-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201110_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawimgsreport',
            name='images_size_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее размер изображений ценников'),
        ),
    ]
